### ISSUE TITLE
Thorough review of CloudGraphs.outneighbors

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#105]

**Comment by dehann** [comment]
cc @GearsAD , can we always rely on `()-[:DEPENDENCE]-()`?

**Comment by dehann** [comment]
HI @GearsAD , this issue is probably under a lot of consideration right now via CloudGraphsDFG?

**Comment by GearsAD** [comment]
Hi @dehann,

Okay, really good question. I'd like that:
* Outneighbors returns all nodes in the graph
* It does not return the SESSION node (i.e. the session anchor)
* It does work with multisession prime nodes 

So I've put in that all factor--variable edges are set with :FACTORGRAPH, not :DEPENDENCE (for clarity). We'll maintain that when we do multisession.

E.g.
![image](https://user-images.githubusercontent.com/6854507/59552598-b6e20e80-8f4e-11e9-9eae-25a01d465ee4.png)

Any concerns?

**Comment by dehann** [comment]
Provided by DFG v0.4.x
