### ISSUE TITLE
How to use the multi-hypothesis feature?

### ISSUE THREAD

**Issue by keevindoherty** [JuliaRobotics/Caesar.jl#141]
Is there a simple example making use of the multi-hypothesis API?

**Comment by dehann** [comment]
lets say you have an ambiguous `pp = Pose2Point2BearingRange(...)` to one of two landmarks, you can update the `addFactor!` part as follows:
```julia
addFactor!(fg, [:x1;:l1;:l2], pp, multihypo=[1.0;0.5;0.5])
```
Assuming you are working from pose `:x1` and ambiguity exists between `:l1 / :l2`.  The intended use of the `multihypo` keyword is a simplification for bimodal factors. (Future versions will implicitly allow n-modal definition via the 'easy API').  In this example the ambiguity is taken as 0.5/0.5 split between `:l1 / :l2`.  The syntax requires you to specify the 1.0 certainty in `:x1`.  You should be able to use this ambiguity definition with any factor in a bimodal fashion.  Note this interface is a convenience method and the internals of multimodal-iSAM allow for far greater complexity.

Should probably add an example in the documentation.

**Comment by GearsAD** [comment]
+1 for doc example

**Comment by dehann** [comment]
will be added once the fractional null-hypothesis update in IIF is completed -- JuliaRobotics/IncrementalInference.jl#248

**Comment by dehann** [comment]
really need to document for JuliaRobotics/RoME.jl#342

**Comment by dehann** [comment]
https://juliarobotics.org/Caesar.jl/latest/concepts/dataassociation/
