### ISSUE TITLE
improve `executeQuery` in two ways

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#150]
https://github.com/JuliaRobotics/Caesar.jl/blob/5784e15473bee66a9fb858ae16502ef50c6239c5/src/cloudgraphs/CloudGraphIntegration.jl#L50
Tasks are:
- [ ] `executeQuery` should become `executeQuery!`,
- [ ] ensure `Neo4j.commit` always occurs in `executeQuery!`

cc @GearsAD

**Comment by dehann** [comment]
see glesica/Neo4j.jl#12

**Comment by GearsAD** [comment]
Should be resolved as part of #149

**Comment by GearsAD** [comment]
I think so.
