### ISSUE TITLE
Labels tags or ids

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#251]

**Comment by dehann** [comment]
When do we use labels and tags for a node?  And why do softtypes have labels too?

**Comment by dehann** [comment]
Graphs.jl has vert .index and vert .label 
Then I added label to addVariable for db stuff. Then I added softtypes. Then I added labels to softtypes for some reason, and now we confused

**Comment by dehann** [comment]
Johan, I think punchline is labels are so useful in db that we want them in memory too — it was never built that way ... clearly we have to do a better job of that.  We likely won’t go as fancy as the db, but at least something.  You are rightly asking for the labeltags to be available and persistent in memory

**Comment by dehann** [comment]
Cc @GearsAD @Affie

**Comment by Affie** [comment]
for in memory factor graphs it would be handy to distinguish between different types, eg. poses, landmarks etc.

**Comment by GearsAD** [comment]
As per Hangout conversation:

- Labels in memory should be 1st class citizens, as they are in DB. This is an issue we need to address, probably in CloudGraphs.
- Let's call the x1/l1 marker an ID or a tag to differentiate

**Comment by dehann** [comment]
+1 for :x1/:l2/:p4 is a tag

**Comment by Affie** [comment]
if you call `addNode!(fg, :l1, Pose2, labels=["LANDMARK";])` on local fg, what happens to the label currently? The equivalent Graff call `addVariable(...` keeps it.

**Comment by GearsAD** [comment]
When you work with in-memory vertices, you'll have:
- vert.index (internal location ID)
- vert.label = x1/x2/etc = node tag
- vert.attributes["data"] = data
- vert.attributes["labels"] = database labels.

Is that correct and good with everyone?

**Comment by dehann** [comment]
Joha, you were asking about Pose2Pose2 overwriting Variable labels?

**Comment by Affie** [comment]
No, that's something else. Still debugging.

**Comment by dehann** [comment]
Okay, will do Pose2Pise2 separately

**Comment by dehann** [comment]
We also have to figure out if softtype has any use.  I used to think (for lack of insight) that pose 2 is likely a “POSE” — that is definitely not true.  So I’m not sure if softtype.label is useful.

My suggestion is we leave the softtype data field there but ignore it and don’t use it.  There only use getData(vert) labels or vert.attributes[“labels”]

**Comment by Affie** [comment]
Do you populate the softtype.label field, if not hard coded in type constructor?

**Comment by dehann** [comment]
Probably not.  I think there is one step at node creation where all the labels get merged and stored.  Will have to check precisely what happens there

**Comment by Affie** [comment]
For Arena I would like to use something like:
```julia
if in("POSE", nodelabels)
	groupsym = :poses #add to poses group
elseif in("LANDMARK", nodelabels)
	groupsym = :landmarks #add to landmarks group
end
```

**Comment by Affie** [comment]
Possibly related in GraffSDK for new variable creation with different labels:
GraffSDK Node:
 - ID: 21955
 - Label: x10
 - Graph Labels: ["**POSE**", "VARIABLE", "...

GraffSDK Node:
 - ID: 21827
 - Label: l0
 - Graph Labels: ["**POSE**", "VARIABLE", "**LANDMARK**", "...

Maybe fixed in https://github.com/JuliaRobotics/RoME.jl/issues/151

**Comment by dehann** [comment]
Yes, the intention was to fix this with JuliaRobotics/RoME.jl#151 .

**Comment by GearsAD** [comment]
From my understanding this is now fixed, and we're going ahead with label = x1, tags = [VARIABLE, SOMETHING], and ID = 74112. I've updated Graff and API, can close?

**Comment by dehann** [comment]
Keeping open until this has been added to Caesar Documentation.  Also added to new Docs kanban.

**Comment by dehann** [comment]
its in the wiki.
