### ISSUE TITLE
Possible loss of factor neighbor information

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#252]
Here is a factor graph where 
ls(fg, :l11)
1-element Array{Symbol,1}:
 :x109l11f1

But

ls(fg, :x3)
5-element Array{Symbol,1}:
 :x2x3f1
 :x3l11f1
 :x3l12f1
 :x3l13f1
 :x3x4f1

How is the factor graph being built?

**Comment by dehann** [comment]
Maybe try
vert = getVert(fg, :l11)
Graphs.out_neighbors(vert, fg.g) ?

**Comment by Affie** [comment]
depending on type of vertex, 
```julia
addNode!(fg, nnode, Pose2, labels=[poselabel])
addFactor!(fg, [pnode;nnode], pp )

addNode!(fg, nnode, Point2, labels=["LANDMARK"])
addFactor!(fg, [pnode;nnode], p2br)
```

**Comment by Affie** [comment]
```julia
Graphs.TargetIterator{GenericIncidenceList{ExVertex,Edge{ExVertex},Dict{Int64,ExVertex},Dict{Int64,Array{Edge{ExVertex},1}}},Array{Edge{ExVertex},1}}(Undirected Graph (515 vertices, 525 edges), Edge{ExVertex}[edge [521]: vertex [510] "l11" -- vertex [511] "x109l11f1"])
```

**Comment by Affie** [comment]
I look like this happens if a new node is made that already exists. Should we add a warning?

**Comment by dehann** [comment]
Just making sure -- the issue is that variable tags (:l1) was being reused?

**Comment by dehann** [comment]
there should be a warning for stepping on the same tag name

**Comment by GearsAD** [comment]
+1, we need checks on duplication etc when building graphs in memory

**Comment by dehann** [comment]
Done
