### ISSUE TITLE
Managing MIME types for bigData storage

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#274]
- [x] Need an example of how to use jpeg vs. png vs. pointcloud.
- [x] Need second example of how to create your own mime type.
- [x] Need an example how to ignore mime type and just dump binary or string data.

**Comment by dehann** [comment]
This is to allows standard feature in Arena.jl etc to work if MIME type is configured properly.

cc @Affie , @GearsAD

**Comment by dehann** [comment]
xref design discussion: https://github.com/JuliaRobotics/Caesar.jl/wiki/Standard-MIME-type-for-bigData----system-wide-integration

**Comment by dehann** [comment]
Hi @Affie , just a refresher on this issue -- I think a lot of this has been done in the recent DFG data interface work?

**Comment by dehann** [comment]
xref JuliaRobotics/DistrubtedFactorGraphs.jl#579

**Comment by Affie** [comment]
We can currently do this one:

> Need an example how to ignore mime type and just dump binary or string data.

I think we should support a few other natively and provide examples of how to add more.
So agree with fist post.
