### ISSUE TITLE
odd man out behavior? appears to be related to sibling cliqs issue

### ISSUE THREAD

**Issue by mc2922** [JuliaRobotics/Caesar.jl#374]
script: [examples/marine/asv/kayaks/smallRangeError.jl](https://github.com/JuliaRobotics/Caesar.jl/blob/dynSAS/examples/marine/asv/kayaks/smallRangeError.jl)

EDIT assume: dynSAS branch...

Adding an odometry chain: x1  - x9
Priors added on x1 and x9
Range factors added on x1, x4 and x7 to beacon l1

Resulting in x4 being an odd man out of the chain?

![image](https://user-images.githubusercontent.com/11624503/61426917-0068a500-a8d1-11e9-8a42-c8462e6e440a.png)
![image](https://user-images.githubusercontent.com/11624503/61427058-8c7acc80-a8d1-11e9-8e45-5502f520b2b7.png)

Check the range sampler on :x4, looks reasonable
![image](https://user-images.githubusercontent.com/11624503/61426984-3f96f600-a8d1-11e9-8fa7-2ed55c6cbbab.png)

bit of looking the marginals on the tree:
![image](https://user-images.githubusercontent.com/11624503/61427007-61907880-a8d1-11e9-9831-98492f27d2de.png)

leaf clique with frontal l1 passes up to x1 this msg.
![image](https://user-images.githubusercontent.com/11624503/61427256-5a1d9f00-a8d2-11e9-9260-21c39c291ffa.png)

and up passes to x4 this msg:
![image](https://user-images.githubusercontent.com/11624503/61427152-fabf8f00-a8d1-11e9-9e6f-424dad38e5b8.png)

because x1 has the prior? 

EDIT: THIS TREE FIGURE WAS LATER THOUGHT TO BE SUSPECT, SEE BELOW.  This tree was created with priors on :x1 and :x8, but later changed to :x1 and :x9.

**Comment by dehann** [comment]
Right, so looks like this example is using the tree initialization (as we'd like to).  The up message on :x1 from clique (:l1) is based on the prior, however, only a partial solve is for :x4 and :x7 can be done at the leaff clique as a first step using the range measurements in that clique.  The CSM logic must either accept this for upsolve, or first try provide more information with downward messages before accepting values as the final upsolve result on (:l1).

Also note that just above :x4 is a frontal in (:x4) and should be set there while also considering the odometry factors to :x5, etc also.  Thanks very much for the example and the input -- it defintely helps isolate and guide the CSM fixes going on.  Just FYI:  ongoing work under issues such as JuliaRobotics/IncrementalInference.jl#344.

**Comment by dehann** [comment]
The fact that :x4 is so way out after downsolve definitely means all the information from factors connected to :x4 are not making it into the final result for some reason.  And, would suggest there is a sequencing issue with CSM maybe skipping a step as you suggested yesterday.

**Comment by dehann** [comment]
I'm getting a different tree for some reason??
![Screenshot from 2019-08-03 01-31-32](https://user-images.githubusercontent.com/6412556/62407942-784ff400-b58e-11e9-8b0d-6fcad5c2743c.png)

**Comment by mc2922** [comment]
Latest IIF result: 
![image](https://user-images.githubusercontent.com/11624503/62408057-3798b080-b577-11e9-998f-f47845844351.png)

**Comment by mc2922** [comment]
Fixed by using odometry or prior based autoinit

![image](https://user-images.githubusercontent.com/11624503/62408246-5e0c1b00-b57a-11e9-8856-3bf04cb3e4df.png)

**Comment by dehann** [comment]
Likely fixed in IIF v0.7.7 or greater.
