### ISSUE TITLE
[FEATURE] read in g2o files for standard datasets

### ISSUE THREAD

**Issue by tonioteran** [JuliaRobotics/Caesar.jl#498]
the reverse operation of #497

**Comment by dehann** [comment]
I think there should be a "RobotDatasetsSLAM.jl" package.  I can help with creating that.

**Comment by tonioteran** [comment]
sounds like a good idea! I'll leave the setting up to you, since I'm quite the noob!

**Comment by dehann** [comment]
implemented in RoME
