### ISSUE TITLE
Looking for example of semantic factors

### ISSUE THREAD

**Issue by Sanghyun-Cha** [JuliaRobotics/Caesar.jl#631]
I'm studying on semantic SLAM, and recently, I read following papers.

- Kevin Doherty, Dehann Fourie, John Leonard, “Multimodal Semantic SLAM with Probabilistic Data Association”, 2019 International Conference on Robotics and Automation (ICRA), 2019.
- Dehann Fourie, John Leonard, Michael Kaess. "A nonparametric belief solution to the Bayes tree." 2016 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS). IEEE, 2016.

Is there some example code about using semantic factors?

**Comment by dehann** [comment]
see reply in JuliaRobotics/RoME.jl#342

**Comment by Sanghyun-Cha** [comment]
Thanks a lot!
