### ISSUE TITLE
Getting Started with Caesar.jl - Initial Conditions

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/Caesar.jl#71]
For beginner users: When creating a robot-side process to push data into Caesar.jl, should I always assume that every sessions starts at the origin and that subsequent poses are relative to that root vertex?

This affects whether I should create a pose the moment I start. If so, what happens when the factor graph is refined? Bigger question, but this is a start to a longer discussion.

**Comment by dehann** [comment]
see documentation example here for naive solution:
http://www.juliarobotics.org/Caesar.jl/latest/tut_hexagonal2d.html
