### ISSUE TITLE
Getting Started with Caesar.jl - When should I create poses?

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/Caesar.jl#72]
For beginner users - when should I create poses? 

Majority of sensors sample quickly - e.g. 30 samples/sec - should I save a pose every time I get an update? The majority of that data is redundant, but is there a good rule-of-thumb for selecting what to push as a new pose?

**Comment by dehann** [comment]
Pose triggers can be based on distance, rotation, or time separation.  Maybe we should add a short discussion to the documentation.
