### ISSUE TITLE
Move these functions to CloudGraphs.jl

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/Caesar.jl#73]
https://github.com/dehann/Caesar.jl/blob/master/src/cloudgraphs/CloudGraphIntegration.jl

**Comment by dehann** [comment]
Thanks, I think CloudGraphs.jl should work at the level of Graphs.ExVertex and CloudVertex, and leave the robotics related calls in either Caesar.jl or RoME.jl. I guess we will see in time how the functions in `CloudGraphIntegration.jl` file should be factored. Thanks!

**Comment by dehann** [comment]
Hi, is this still in play?  At what point should we start removing functions from `Caesar/CloudGraphIntegration.jl`?

**Comment by GearsAD** [comment]
Hmm, I'm now rethinking. These functions are not db specific - ideally you should be able to do them without knowing that there's a db underneath -> They're technically there because the CloudGraphs layer is too thin. Let's discuss but I think we grow DFG and slowly deprecate the db-specific stuff?

**Comment by dehann** [comment]
Agreed, DFG is it I think.  Will add a note to the IIF/DFG project to point here.

**Comment by dehann** [comment]
This should be done with DFG v0.4.x
