### ISSUE TITLE
Manifolds page in CJL docs

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/Caesar.jl#817]
Panel feedback for ICRA suggested we have info on non-Gaussian on manifold, I suggest we do in directly in the CJL Docs as part of next step points from the tutorials.

**Comment by Affie** [comment]
Needed for tutorial 1 in the "Additional Resources" section

**Comment by dehann** [comment]
xref:
- https://github.com/JuliaRobotics/RoME.jl/issues/574
